# Generated by Django 3.1 on 2020-08-14 17:00

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('general', 'General'), ('beauty', 'Beauty'), ('trends', 'Trends'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('food', 'Food'), ('entrepreneur', 'Entrepreneur'), ('fashion-pictorial', 'Fashion Pictorial'), ('health', 'Health'), ('mens-corner', 'Men'), ('lifestyle', 'Lifestyle')], default='general', max_length=17)),
                ('category_description', models.TextField(max_length=3000)),
                ('category_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/articles/photos'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=10, unique=True, verbose_name='Issue Number')),
                ('issue_pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issue Publication Date')),
                ('issue_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Issue Status')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_id', models.CharField(max_length=10, verbose_name='Magazine Name')),
                ('mag_date1', models.DateField(verbose_name='Magazine Date')),
                ('mag_date2', models.DateField(verbose_name='Magazine Date')),
                ('mag_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=10, unique=True, verbose_name='Article ID')),
                ('header_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/articles/photos'), upload_to='', verbose_name='Head Image')),
                ('title', models.CharField(max_length=10, verbose_name='Article Title')),
                ('summary', models.CharField(max_length=50, verbose_name='Article Summary')),
                ('body', models.TextField(verbose_name='Article Body')),
                ('body_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/articles/photos'), upload_to='', verbose_name='Article Image')),
                ('slug', models.SlugField(max_length=20, unique_for_date='publish_date')),
                ('article_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Issue Status')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issue Publication Date')),
                ('article_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.issue')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.category')),
            ],
        ),
    ]
