# Generated by Django 3.1 on 2020-08-17 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('beauty', 'Beauty'), ('trends', 'Travel'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('food', 'Food'), ('entrepreneur', 'Entrepreneur'), ('fashion-pictorial', 'Fashion Pictorial'), ('health', 'Health'), ('men', 'Mens Corner'), ('lifestyle', 'Lifestyle'), ('general', 'General')], default='general', max_length=20, verbose_name='Category Name')),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(max_length=250)),
                ('category_link', models.SlugField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('publish_date', models.DateField()),
                ('magazine_link', models.SlugField(max_length=25, unique_for_date='publish_date')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('news_link', models.SlugField(max_length=25, unique_for_date='date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.category')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('subheading1', models.CharField(max_length=20)),
                ('body1', models.TextField()),
                ('subheading2', models.CharField(max_length=20)),
                ('body2', models.TextField()),
                ('subheading3', models.CharField(max_length=20)),
                ('body3', models.TextField()),
                ('body_image', models.ImageField(upload_to='uploads/')),
                ('published', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('article_link', models.SlugField(max_length=25, unique_for_date='publish_date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.category')),
                ('magazine_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.magazine')),
            ],
        ),
    ]
