# Generated by Django 3.1 on 2020-08-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
    ]
