# Generated by Django 3.1 on 2020-08-14 18:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/articles/photos'), upload_to='', verbose_name='Head Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='Article Summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/articles/photos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Issue Number'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_id',
            field=models.CharField(max_length=50, verbose_name='Magazine Name'),
        ),
    ]
