# Generated by Django 3.1 on 2020-08-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20200817_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body1',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='subheading1',
            new_name='subheading',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subheading2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subheading3',
        ),
    ]
