# Generated by Django 3.1 on 2020-08-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20200818_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article list', 'verbose_name_plural': 'Article list'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Authors', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category List', 'verbose_name_plural': 'Category List'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'Magazine Issues', 'verbose_name_plural': 'Magazine Issues'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News Updates', 'verbose_name_plural': 'News Updates'},
        ),
    ]
