# Generated by Django 3.1 on 2020-08-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20200818_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='title',
            new_name='mag_title',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='Author', max_length=25, verbose_name='Author Display Name'),
        ),
    ]
