# Generated by Django 3.1 on 2020-08-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20200818_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('trends', 'Trends'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('food', 'Food'), ('entrepreneur', 'Entrepreneur'), ('fashion-pictorial', 'Fashion Pictorial'), ('health', 'Health'), ('men', 'Mens Corner'), ('lifestyle', 'Lifestyle'), ('general', 'General')], default='general', max_length=20, verbose_name='Category Name'),
        ),
    ]
