# Generated by Django 3.1 on 2020-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_auto_20200819_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_link',
            field=models.SlugField(default='artcle', editable=False, max_length=200, unique=True),
        ),
    ]
