# Generated by Django 3.1 on 2020-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_auto_20200819_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_link',
            field=models.SlugField(default='artcle', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_link',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_link',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
